name: WasteWater
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - appdirs=1.4.4
  - attrs=21.4.0
  - biopython=1.79
  - boost-cpp=1.74.0
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.18.1
  - ca-certificates=2022.9.24
  - certifi=2022.9.24
  - cffi=1.15.0
  - charset-normalizer=2.1.0
  - click=8.1.3
  - colorama=0.4.4
  - configargparse=1.5.3
  - cryptography=37.0.2
  - curl=7.83.1
  - cvxpy=1.2.1
  - cvxpy-base=1.2.1
  - cycler=0.11.0
  - datrie=0.8.2
  - decorator=5.1.1
  - dendropy=4.5.2
  - docutils=0.18.1
  - ecos=2.0.10
  - fonttools=4.33.3
  - freetype=2.10.4
  - freyja=1.3.7
  - giflib=5.2.1
  - gitdb=4.0.9
  - gitpython=3.1.27
  - htslib=1.14
  - icu=70.1
  - idna=3.3
  - importlib-metadata=4.11.4
  - importlib_resources=5.8.0
  - iqtree=1.6.12
  - isa-l=2.30.0
  - ivar=1.3.1
  - joblib=1.1.0
  - jpeg=9e
  - jsonschema=4.6.1
  - jupyter_core=4.10.0
  - keyutils=1.6.1
  - kiwisolver=1.4.2
  - krb5=1.19.3
  - lcms2=2.12
  - ld_impl_linux-64=2.36.1
  - lerc=3.0
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libcbor=0.9.0
  - libcurl=7.83.1
  - libdeflate=1.10
  - libedit=3.1.20191231
  - libev=4.33
  - libffi=3.4.2
  - libfido2=1.11.0
  - libgcc-ng=12.1.0
  - libgfortran-ng=12.1.0
  - libgfortran5=12.1.0
  - libgomp=12.1.0
  - liblapack=3.9.0
  - libnghttp2=1.47.0
  - libnsl=2.0.0
  - libopenblas=0.3.20
  - libpng=1.6.37
  - libprotobuf=3.18.1
  - libssh2=1.10.0
  - libstdcxx-ng=12.1.0
  - libtiff=4.4.0
  - libudev1=249
  - libuuid=2.32.1
  - libwebp=1.2.2
  - libwebp-base=1.2.2
  - libxcb=1.13
  - libzlib=1.2.12
  - lz4-c=1.9.3
  - mafft=7.505
  - matplotlib-base=3.5.2
  - mpi=1.0
  - munkres=1.1.4
  - mysql-connector-c=6.1.11
  - nbformat=5.4.0
  - ncurses=6.3
  - numpy=1.22.4
  - openjpeg=2.4.0
  - openmpi=4.1.4
  - openssh=9.0p1
  - openssl=1.1.1q
  - osqp=0.6.2.post0
  - packaging=21.3
  - pandas=1.4.2
  - pangolin=1.1.14
  - pillow=9.1.1
  - pip=22.1.2
  - plotly=5.8.2
  - psutil=5.9.1
  - pthread-stubs=0.4
  - pycparser=2.21
  - pyopenssl=22.0.0
  - pyparsing=3.0.9
  - pyrsistent=0.18.1
  - pysocks=1.7.1
  - python=3.10.4
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.15.3
  - python_abi=3.10
  - pytools=2020.1
  - pytz=2022.1
  - pyyaml=6.0
  - qdldl-python=0.1.5
  - ratelimiter=1.2.0
  - readline=8.1.2
  - requests=2.28.1
  - samtools=1.6
  - scipy=1.8.1
  - scs=3.2.0
  - setuptools=62.3.4
  - six=1.16.0
  - smmap=3.0.5
  - snakemake-minimal=5.13.0
  - sqlite=3.38.5
  - tenacity=8.0.1
  - tk=8.6.12
  - toposort=1.7
  - tqdm=4.64.0
  - traitlets=5.3.0
  - treelib=1.6.1
  - typing_extensions=4.2.0
  - tzdata=2022a
  - ucsc-fatovcf=426
  - unicodedata2=14.0.0
  - urllib3=1.26.9
  - usher=0.5.4
  - wheel=0.37.1
  - wrapt=1.14.1
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xz=5.2.5
  - yaml=0.2.5
  - zipp=3.8.0
  - zlib=1.2.12
  - zstd=1.5.2
  - pip:
    - lineages==2020-05-19
