#!/usr/bin/env bash

Help() {
    echo ""
    echo "Wastewater Tools"
    echo "Usage: wastewatertools <module> [module options]"
    echo ""
    echo "Modules:"
    echo ""
    echo "  - freyja_pipeline"
    echo "  - MORE TO BE ADDED"
    echo ""
    echo "To view this message:"
    echo "  wastewatertools -h"
    echo ""
    echo "To view module help messages:"
    echo "  amplify <module> -h"
    echo ""
}
SRC_DIR=$(dirname ${BASH_SOURCE})

if [ "$1" = freyja_pipeline ]; then
    "$SRC_DIR"/bin/freyja-pipeline.sh ${@:2}
elif [ "$1" = parse_gisaid ]; then
    python3 "$SRC_DIR"/bin/scripts/parse_gisaid_data.py ${@:2}
elif [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    Help
else 
    echo "Module "$1" does not exist"
    Help
fi